### ISSUE TITLE
File.Error due to file name (Elixir.Reactor.Dsl.Reactor.Switch.Reactor.Matches.Matches?.Options.beam)

### ISSUE THREAD

**Issue by puruzio** [ash-project/reactor#75]
**Describe the bug**
Compiling reactor fails on Windows with the following file IO error. It appears to be due to the question mark in the file name.:

```
==> reactor
Compiling 54 files (.ex)
** (EXIT from #PID<0.104.0>) an exception was raised:
    ** (File.Error) could not write to file "c:/Users/user1/my_app/_build/dev/lib/reactor/ebin/Elixir.Reactor.Dsl.Reactor.Switch.Reactor.Matches.Matches?.Options.beam": no such file or directory
        (elixir 1.15.5) lib/file.ex:1117: File.write!/3
        (elixir 1.15.5) lib/kernel/parallel_compiler.ex:282: anonymous fn/3 in Kernel.ParallelCompiler.write_module_binaries/3
        (elixir 1.15.5) lib/enum.ex:1260: anonymous fn/3 in Enum.flat_map/2
        (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
        (elixir 1.15.5) lib/enum.ex:2522: Enum.flat_map/2
        (elixir 1.15.5) lib/kernel/parallel_compiler.ex:209: Kernel.ParallelCompiler.spawn_workers/3
        (mix 1.15.5) lib/mix/compilers/elixir.ex:986: anonymous fn/9 in Mix.Compilers.Elixir.compiler_loop/6


```

**To Reproduce**
mix compile after reactor is included in mix.exs

**Expected behavior**
No file IO error.

**Runtime**
 - Elixir version 1.15
 - Erlang version 26
 - OS   Windows 11
 - Spark version
 - any related extension versions

**Comment by jimsynz** [comment]
Ahh. This is most likely a Spark bug.  I'll check.

**Comment by jimsynz** [comment]
This should be fixed.
